accumulate_grad_batches: 8
batch_size: 32
data_augmentation_translate_data: false
loss_function: MSE
max_train_epochs: 2
model_name: dumitrescustefan/bert-base-romanian-uncased-v1
training_method: pipeline-biblical-sts
