accumulate_grad_batches: 8
batch_size: 32
data_augmentation_translate_data: false
loss_function: MSE
lr: 1.0e-05
max_train_epochs: 10
model_name: dumitrescustefan/bert-base-romanian-uncased-v1
training_method: pipeline-paraphrase-biblical-sts
