accumulate_grad_batches: 8
batch_size: 32
data_augmentation_translate_data: false
loss_function: MSE
max_train_epochs: 10
model_name: readerbench/RoBERT-base
training_method: pipeline-paraphrase-biblical-sts
