accumulate_grad_batches: 8
batch_size: 32
data_augmentation_translate_data: false
dev_dataset_name: ro-sts
loss_function: MSE
max_train_epochs: 10
model_name: BlackKakapo/t5-base-paraphrase-ro-v2
train_dataset_name: ro-sts
