accumulate_grad_batches: 8
batch_size: 512
data_augmentation_translate_data: false
dev_dataset_name: ro-sts
loss_function: MSE
max_train_epochs: 10
model_name: readerbench/RoBERT-base
train_dataset_name:
- ro-sts
- biblical_01
